name: "VÃ©rification grammaire/orthographe"
on: push
jobs:
  grammaire_et_orthographe:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Installation de grammlint
        run: python -m pip install git+https://gitlab.in2p3.fr/sonny.lion/grammalint.git
      - name: Extraction des fichiers
        uses: actions/checkout@v5
      - name: Execution de grammalint
        run: python -m grammalint --skip-frontmatter-keys auteur image favori -i recettes/**/*.md

